no message

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
+# bin/detect <build-dir>
 
-# Install python3-dev package
-apt-get update
-apt-get install -y python3-dev
+if [[ -f "$1/Aptfile" ]]; then
+  echo "Mythril add-apt-repository"
+  exit 0
+else
+  echo "Could not find an 'Aptfile'! Please ensure it exists and is checked into Git." >&2
+  exit 1
+fi
