no message

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,4 +1,10 @@
 #!/usr/bin/env bash
 # bin/detect <build-dir>
 
-echo "debug" && exit 0
+if [[ -f "$1/Aptfile" ]]; then
+  echo "Mythril add-apt-repository"
+  exit 0
+else
+  echo "Could not find an 'Aptfile'! Please ensure it exists and is checked into Git." >&2
+  exit 1
+fi
